'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {execFileSync,spawn}=require('node:child_process');
const root=path.resolve(__dirname,'..'),tools=path.join(root,'.test-tools'),log=path.join(tools,'installer-test.log');
fs.writeFileSync(log,'');const note=value=>fs.appendFileSync(log,value+'\n');
const run=(exe,args,extra={})=>execFileSync(exe,args,{windowsHide:true,stdio:'pipe',timeout:60000,...extra});
run(path.join(tools,'PrivateDesktop.exe'),['--check']);
const config=JSON.parse(fs.readFileSync(path.join(tools,'installer-test-config.json'))),current=require('../package.json').version;
const dir=fs.mkdtempSync(path.join(tools,'installer-test-')),installed=path.join(dir,'installed');
const key='HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\'+config.appId+'_is1';
const native=path.join(root,'runtime/UpdateInstaller.exe'),maintenance=path.join(tools,'maintenance.exe');
const setup=()=>run(config.setup,['/VERYSILENT','/SUPPRESSMSGBOXES','/NORESTART','/SP-',`/DIR=${installed}`,`/LOG=${path.join(dir,'setup.log')}`]);
const registered=value=>run('reg.exe',['query',key,'/v',value]).toString();
const digest=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
let standIn=null;
(async()=>{try{
 fs.mkdirSync(installed);fs.writeFileSync(path.join(installed,'my-notes.txt'),'keep me');
 const profile=path.join(dir,'profile-fixture.json');fs.writeFileSync(profile,'dummy settings; never user data');
 setup();assert.match(registered('DisplayVersion'),new RegExp(current.replaceAll('.','\\.')));
 assert(registered('InstallLocation').includes(installed));
 assert(registered('UninstallString').includes('.launcher-install'));
 for(const relative of config.files)assert.equal(digest(path.join(installed,relative)),digest(path.join(root,relative)),relative);
 run(path.join(installed,'Dungeon Blitz Launcher.exe'),['--verify']);
 for(const name of ['Start Menu','Desktop']){
  const link=JSON.parse(run('pwsh.exe',['-NoProfile','-File',path.join(__dirname,'read-shortcut.ps1'),path.join(installed,'.test-shortcuts',name+'.lnk')]).toString());
  assert.equal(link.target,path.join(installed,'Dungeon Blitz Launcher.exe'));assert.equal(link.directory,installed);
 }
 note('PASS fresh install, all payload hashes, Windows app/uninstall registration, both real shortcut files and installed root --verify');
 setup();assert.equal(fs.readFileSync(profile,'utf8'),'dummy settings; never user data');assert.equal(fs.readFileSync(path.join(installed,'my-notes.txt'),'utf8'),'keep me');
 note('PASS reinstall preserves unknown files and external profile fixture');
 const csc='C:/Windows/Microsoft.NET/Framework64/v4.0.30319/csc.exe',fixture=path.join(dir,'fixture.cs'),processFile=path.join(installed,'installer-process-fixture.exe');
 fs.writeFileSync(fixture,'public static class Fixture {public static void Main(){System.Threading.Thread.Sleep(60000);}}');
 run(csc,['/nologo','/target:exe',`/out:${processFile}`,fixture]);
 standIn=spawn(processFile,[],{windowsHide:true,stdio:'ignore'});
 await new Promise(resolve=>setTimeout(resolve,200));
 assert.throws(setup);assert.equal(standIn.exitCode,null);assert.match(fs.readFileSync(path.join(dir,'setup.log'),'utf8'),/Close the installed Dungeon Blitz Launcher/);
 standIn.kill();await new Promise(resolve=>standIn.once('exit',resolve));standIn=null;fs.unlinkSync(processFile);
 note('PASS running installed process blocks installation without being killed');
 const state=path.join(installed,'.launcher-install'),ledger=path.join(state,'files-'+current+'.txt'),original=fs.readFileSync(ledger),report=path.join(dir,'maintenance-result.txt');
 fs.writeFileSync(ledger,'../profile-fixture.json\n');assert.throws(()=>run(maintenance,['cleanup',installed,report]));
 assert.equal(fs.readFileSync(profile,'utf8'),'dummy settings; never user data');assert(fs.existsSync(path.join(installed,'Dungeon Blitz Launcher.exe')));fs.writeFileSync(ledger,original);
 const junction=path.join(dir,'junction');fs.symlinkSync(installed,junction,'junction');
 assert.throws(()=>run(maintenance,['cleanup',junction,report]));fs.unlinkSync(junction);
 note('PASS traversal and junction cleanup rejected before any application deletion');
 const future='0.12.1',source=path.join(dir,'update-source'),futureBuild=`release/${future}/Dungeon Blitz Launcher-win32-x64`,futureExe=path.join(source,futureBuild,'Dungeon Blitz Launcher.exe');fs.mkdirSync(path.dirname(futureExe),{recursive:true});
 fs.writeFileSync(fixture,`[assembly:System.Reflection.AssemblyFileVersion("${future}.0")] public static class Fixture{public static int Main(){return 0;}}`);
 run(csc,['/nologo','/target:winexe',`/out:${futureExe}`,fixture]);
 const launcherSource=path.join(dir,'launcher.cs');fs.writeFileSync(launcherSource,fs.readFileSync(path.join(root,'src/Launcher.cs'),'utf8').replaceAll('@@VERSION@@',future).replaceAll('@@MAJOR@@','0').replaceAll('@@MINOR@@','12').replaceAll('@@PATCH@@','1'));
 run(csc,['/nologo','/target:winexe','/r:System.Windows.Forms.dll',`/out:${path.join(source,'Dungeon Blitz Launcher.exe')}`,launcherSource]);
 fs.writeFileSync(path.join(source,futureBuild,'future-resource.txt'),'future update test fixture');
 const files=['Dungeon Blitz Launcher.exe',futureBuild+'/Dungeon Blitz Launcher.exe',futureBuild+'/future-resource.txt'].map(relative=>({path:relative,size:fs.statSync(path.join(source,relative)).size,sha256:digest(path.join(source,relative))}));
 const update=path.join(dir,'update.json');fs.writeFileSync(update,JSON.stringify({version:future,source,destination:installed,pid:2147483647,files}));run(native,['install',update,'close']);
 assert.match(registered('DisplayVersion'),/0\.12\.1/);assert(fs.existsSync(path.join(state,'files-'+future+'.txt')));run(path.join(installed,'Dungeon Blitz Launcher.exe'),['--verify']);
 assert.throws(setup);assert.match(fs.readFileSync(path.join(dir,'setup.log'),'utf8'),/newer Dungeon Blitz Launcher/);
 note('PASS updater records new managed files, refreshes Windows version, keeps previous build and rejects installer downgrade');
 const uninstall=path.join(state,'unins000.exe');run(uninstall,['/VERYSILENT','/SUPPRESSMSGBOXES','/NORESTART',`/LOG=${path.join(dir,'uninstall.log')}`]);
 for(const relative of [...config.files,...files.map(file=>file.path)])assert(!fs.existsSync(path.join(installed,relative)),relative+' must be uninstalled');
 assert(!fs.existsSync(path.join(installed,'Dungeon Blitz Launcher.previous.exe')));assert(!fs.existsSync(path.join(installed,'.test-shortcuts')));assert.throws(()=>registered('DisplayVersion'));
 assert.equal(fs.readFileSync(path.join(installed,'my-notes.txt'),'utf8'),'keep me');assert.equal(fs.readFileSync(profile,'utf8'),'dummy settings; never user data');
 note('PASS normal uninstaller removes current/previous/auto-updated builds, shortcuts and registration; retains unrelated files and profile fixture');
 fs.writeFileSync(path.join(tools,'installer-test-result.json'),JSON.stringify({passed:true,version:current,isolatedDesktop:true,testIdentity:config.appId,directory:dir,managedFiles:config.files.length},null,2));
}catch(error){note(error.stack);process.exitCode=1;}finally{if(standIn)standIn.kill();}})();
